### ISSUE TITLE
missing run or map statement

### ISSUE THREAD

**Issue by bgr11n** [rkh/almost-sinatra#21] opened 2015-06-13 18:20 UTC
I'm getting this error when trying to visit '/' or '/hello'

```
Internal Server Error

missing run or map statement
WEBrick/1.3.1 (Ruby/2.2.0/2014-12-25) at localhost:4567
```

Do you know how to fix this?

**Comment by Thermatix** [comment] 2015-08-12 10:58
Probably because you need to run it from a rackup file.

**Comment by Thermatix** [comment] 2015-08-12 10:58
Probably because AS needs to be run from a rackup file (where `run` and `map` exist).

**Comment by AlessandroMinali** [comment] 2023-03-24 15:29
I think issue needs to be reopened. With ruby 3 and latest rack 2 as of today I am getting this problem again.

**Comment by rkh** [comment] 2023-03-31 18:08
I think #14 might address this, but it's been a while, so not sure.

**Comment by AlessandroMinali** [comment] 2023-10-11 03:37
We can close this now. The good folks at [@ruby ](https://github.com/ruby/ruby) and [@rack](https://github.com/rack/rack) have done great work to make this working.
Confirmed working with the `ruby 3.2.2` and `rack 2.2.8`

**Closed** 2023-10-13 14:37 UTC
